import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';
import jsPDF from 'npm:jspdf@4.2.1';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { distributionIds, clientName } = await req.json();

    if (!distributionIds || distributionIds.length === 0) {
      return Response.json({ error: 'No form submissions selected' }, { status: 400 });
    }

    const distributions = await base44.entities.FormDistribution.list();
    const selectedDistributions = distributions.filter(d => distributionIds.includes(d.id));

    if (selectedDistributions.length === 0) {
      return Response.json({ error: 'No distributions found' }, { status: 404 });
    }

    const doc = new jsPDF({ unit: 'pt', format: 'letter' });
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const margin = 48;
    const contentW = pageW - margin * 2;

    let y = margin;

    // ── Header banner ────────────────────────────────────────────────────────────
    doc.setFillColor(26, 58, 92); // navy
    doc.rect(0, 0, pageW, 90, 'F');

    // Logo circle
    doc.setFillColor(0, 151, 167); // teal
    doc.circle(margin + 20, 45, 20, 'F');
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('LC', margin + 20, 50, { align: 'center' });

    // Agency name
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('Lewis County Autism Coalition', margin + 50, 35);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(178, 235, 242);
    doc.text('LCAC Connect — Clinical Documentation System', margin + 50, 55);

    // Right side: Title
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(249, 168, 37); // gold
    doc.text('FORM SUBMISSIONS REPORT', pageW - margin, 35, { align: 'right' });

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(178, 235, 242);
    doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), pageW - margin, 55, { align: 'right' });

    y = 120;

    // ── Client Info Box ────────────────────────────────────────────────────────────
    doc.setFillColor(224, 247, 250); // teal-50
    doc.roundedRect(margin, y, contentW, 45, 4, 4, 'F');

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 105, 120);
    doc.text('Client Name:', margin + 10, y + 20);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(26, 58, 92);
    doc.text(clientName, margin + 80, y + 20);

    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 105, 120);
    doc.text('Total Forms:', margin + 10, y + 35);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(26, 58, 92);
    doc.text(String(selectedDistributions.length), margin + 80, y + 35);

    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 105, 120);
    doc.text('Generated By:', pageW / 2 + 20, y + 20);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(26, 58, 92);
    doc.text(user.full_name || user.email, pageW / 2 + 100, y + 20);

    y += 65;

    // ── Forms Section ────────────────────────────────────────────────────────────
    selectedDistributions.forEach((dist, index) => {
      if (y + 80 > pageH - 80) {
        addFooter(doc, pageW, pageH, margin);
        doc.addPage();
        y = margin;
      }

      // Form header
      doc.setFillColor(0, 151, 167); // teal
      doc.rect(margin, y, contentW, 25, 'F');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 255, 255);
      doc.text(`Form ${index + 1}: ${dist.form_title}`, margin + 10, y + 16);
      y += 35;

      // Form details
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 105, 120);

      const details = [
        { label: 'Client:', value: dist.client_name },
        { label: 'Email:', value: dist.client_email },
        { label: 'Type:', value: dist.form_type },
        { label: 'Sent:', value: new Date(dist.sent_date).toLocaleDateString() },
        { label: 'By:', value: dist.sent_by || 'N/A' },
      ];

      details.forEach((d) => {
        doc.text(d.label, margin + 10, y);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(26, 58, 92);
        doc.text(d.value, margin + 80, y);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 105, 120);
        y += 12;
      });

      y += 5;

      // Status
      doc.setFillColor(255, 249, 232); // gold-light
      doc.rect(margin, y, contentW, 20, 'F');
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(249, 168, 37); // gold
      doc.text('Status:', margin + 10, y + 14);
      doc.setTextColor(26, 58, 92);
      const statusText = dist.completion_status === 'completed' ? '✓ Signed' : 'Pending';
      doc.text(statusText, margin + 80, y + 14);
      y += 30;

      // Separator
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.5);
      doc.line(margin, y, margin + contentW, y);
      y += 15;
    });

    // ── Footer ────────────────────────────────────────────────────────────────────
    addFooter(doc, pageW, pageH, margin);

    const pdfBytes = doc.output('arraybuffer');

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename=LCAC_FormSubmissions_${clientName}_${new Date().toISOString().split('T')[0]}.pdf`,
      },
    });
  } catch (error) {
    console.error('Error generating PDF:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});

function addFooter(doc, pageW, pageH, margin) {
  doc.setFillColor(241, 245, 249);
  doc.rect(0, pageH - 36, pageW, 36, 'F');
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('Lewis County Autism Coalition — Confidential Clinical Document — LCAC Connect', pageW / 2, pageH - 20, { align: 'center' });
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageW / 2, pageH - 10, { align: 'center' });
}