import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';
import jsPDF from 'npm:jspdf@4.2.1';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { clientIds, reportTitle, reportPeriod } = await req.json();

    if (!clientIds || clientIds.length === 0) {
      return Response.json({ error: 'No clients selected' }, { status: 400 });
    }

    const allClients = await base44.entities.Client.list();
    const selectedClients = allClients.filter(c => clientIds.includes(c.id));

    if (selectedClients.length === 0) {
      return Response.json({ error: 'No clients found' }, { status: 404 });
    }

    const allDistributions = await base44.entities.FormDistribution.list();
    const allSubmissions = await base44.entities.Submission.list('-created_date', 1000);

    const doc = new jsPDF({ unit: 'pt', format: 'letter' });
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const margin = 48;
    const contentW = pageW - margin * 2;

    let y = margin;

    // ── Cover Page Header ────────────────────────────────────────────────────────
    doc.setFillColor(26, 58, 92); // navy
    doc.rect(0, 0, pageW, 110, 'F');

    // Logo
    doc.setFillColor(0, 151, 167); // teal
    doc.circle(margin + 25, 55, 22, 'F');
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('LC', margin + 25, 62, { align: 'center' });

    // Title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('Lewis County Autism Coalition', margin + 60, 40);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(178, 235, 242);
    doc.text('LCAC Connect — Clinical Documentation System', margin + 60, 62);

    y = 140;

    // Report Title
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(26, 58, 92);
    doc.text('CLIENT RECORDS REPORT', margin, y);
    y += 25;

    // Report Info
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    if (reportTitle) {
      doc.text(reportTitle, margin, y);
      y += 15;
    }

    if (reportPeriod) {
      doc.text(`Reporting Period: ${reportPeriod}`, margin, y);
      y += 10;
    }

    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
    y += 8;
    doc.text(`Generated By: ${user.full_name || user.email}`, margin, y);
    y += 25;

    // ── Summary Box ──────────────────────────────────────────────────────────────
    doc.setFillColor(224, 247, 250); // teal-50
    doc.roundedRect(margin, y, contentW, 60, 4, 4, 'F');

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 105, 120);
    doc.text('REPORT SUMMARY', margin + 12, y + 18);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(26, 58, 92);

    let totalForms = 0;
    selectedClients.forEach(client => {
      const clientSubs = allSubmissions.filter(s => s.client_id === client.id);
      totalForms += clientSubs.length;
    });

    doc.text(`Total Clients: ${selectedClients.length}`, margin + 12, y + 35);
    doc.text(`Total Form Submissions: ${totalForms}`, pageW / 2 + 10, y + 35);
    doc.text(`Report Generated: ${new Date().toLocaleDateString()}`, margin + 12, y + 50);

    y += 80;

    // ── Client Records ───────────────────────────────────────────────────────────
    selectedClients.forEach((client, idx) => {
      if (y + 100 > pageH - 70) {
        addFooter(doc, pageW, pageH, margin);
        doc.addPage();
        y = margin;
      }

      // Client header
      doc.setFillColor(0, 151, 167); // teal
      doc.rect(margin, y, contentW, 28, 'F');
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 255, 255);
      doc.text(`${idx + 1}. ${client.legal_first_name} ${client.legal_last_name}`, margin + 12, y + 18);
      y += 38;

      // Demographics
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 105, 120);

      const demoFields = [
        ['Legal Name:', `${client.legal_first_name} ${client.legal_last_name}`],
        ['Date of Birth:', client.dob ? new Date(client.dob).toLocaleDateString() : '—'],
        ['Email:', client.email || '—'],
        ['Phone:', client.primary_phone || '—'],
        ['Address:', `${client.address || '—'}, ${client.city || ''} ${client.state || ''} ${client.zip || ''}`.replace(/,\s*$/, '')],
        ['Status:', client.status || 'Active'],
        ['Caregiver:', client.caregiver_name || '—'],
        ['Assigned To:', client.assigned_to || 'Unassigned'],
      ];

      demoFields.forEach(([label, value]) => {
        if (y + 12 > pageH - 70) {
          addFooter(doc, pageW, pageH, margin);
          doc.addPage();
          y = margin;
        }

        doc.text(label, margin + 12, y);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(26, 58, 92);
        const valLines = doc.splitTextToSize(String(value), contentW - 110);
        doc.text(valLines, margin + 110, y);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 105, 120);
        y += 10;
      });

      y += 8;

      // Form History
      const clientForms = allSubmissions.filter(s => s.client_id === client.id);
      if (clientForms.length > 0) {
        if (y + 40 > pageH - 70) {
          addFooter(doc, pageW, pageH, margin);
          doc.addPage();
          y = margin;
        }

        doc.setFillColor(255, 252, 232); // gold-light
        doc.rect(margin, y, contentW, 20, 'F');
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(249, 168, 37);
        doc.text(`FORM HISTORY (${clientForms.length} submissions)`, margin + 8, y + 14);
        y += 25;

        clientForms.slice(0, 5).forEach((form, fidx) => {
          if (y + 10 > pageH - 70) {
            addFooter(doc, pageW, pageH, margin);
            doc.addPage();
            y = margin;
          }

          doc.setFontSize(8);
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(100, 116, 139);
          const date = form.created_date ? new Date(form.created_date).toLocaleDateString() : '—';
          doc.text(`${fidx + 1}. ${form.form_type || 'Unknown'} (${form.status || 'Complete'})`, margin + 12, y);
          doc.setFont('helvetica', 'normal');
          doc.setTextColor(148, 163, 184);
          doc.text(date, pageW - margin - 50, y);
          y += 10;
        });

        if (clientForms.length > 5) {
          doc.setFontSize(8);
          doc.setTextColor(148, 163, 184);
          doc.text(`+${clientForms.length - 5} more submissions`, margin + 12, y);
          y += 8;
        }

        y += 5;
      }

      // Separator
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.5);
      doc.line(margin, y, margin + contentW, y);
      y += 15;
    });

    // ── Final Footer ─────────────────────────────────────────────────────────────
    addFooter(doc, pageW, pageH, margin);

    const pdfBytes = doc.output('arraybuffer');
    const fileName = `LCAC_ClientRecords_${new Date().toISOString().split('T')[0]}.pdf`;

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename=${fileName}`,
      },
    });
  } catch (error) {
    console.error('Error generating PDF:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});

function addFooter(doc, pageW, pageH, margin) {
  doc.setFillColor(241, 245, 249);
  doc.rect(0, pageH - 36, pageW, 36, 'F');
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('Lewis County Autism Coalition — Confidential Clinical Document — LCAC Connect', pageW / 2, pageH - 20, { align: 'center' });
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageW / 2, pageH - 10, { align: 'center' });
}